### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by mwmasterweaks** [jecovier/vue-json-excel#112]
after I import **JsonExcel from "vue-json-excel"**
I get this error:
ReferenceError: regeneratorRuntime is not defined
    at eval (JsonExcel.vue?3b42:128)
    at eval (JsonExcel.vue?3b42:128)
    at Object.<anonymous> (build.js:2509)
    at __webpack_require__ (build.js:679)
    at fn (build.js:89)
    at eval (JsonExcel.vue?253d:1)
    at Object.<anonymous> (build.js:4042)
    at __webpack_require__ (build.js:679)
    at fn (build.js:89)
    at eval (281:9)

how to fix this?

**Comment by mwmasterweaks** [comment]
now I get this error

> Failed to compile.

./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-json-excel/JsonExcel.vue
Module build failed: TypeError: D:/website/scheduler/front/node_modules/vue-json-excel/JsonExcel.vue: t.cloneNode is not a function
    at PluginPass.Method (D:\website\scheduler\front\node_modules\@babel\plugin-transform-regenerator\node_modules\regenerator-transform\lib\visit.js:31:56)
    at newFn (D:\website\scheduler\front\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (D:\website\scheduler\front\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\website\scheduler\front\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\website\scheduler\front\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (D:\website\scheduler\front\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (D:\website\scheduler\front\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (D:\website\scheduler\front\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (D:\website\scheduler\front\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (D:\website\scheduler\front\node_modules\babel-traverse\lib\path\context.js:115:19)
 @ ./node_modules/vue-json-excel/JsonExcel.vue 4:0-93 5:0-106
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/ticket/Ticket_List.vue
 @ ./src/components/ticket/Ticket_List.vue
 @ ./src/routes.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
>

**Comment by jecovier** [comment]
There is no cloneNode reference in the code and I couldn't reproduce the error, maybe was a problem with donwload.js that is a dependency for this component.
